webhooks:
  rss: FEISHU_HOOK_RSS
  webpage: FEISHU_HOOK_WEBPAGE

tasks:
  - name: 月光博客 RSS
    slug: williamlong.info
    type: rss
    url: https://www.williamlong.info/rss.xml
    webhook: rss
    parser: auto

  - name: 芳姐保健汤 RSS
    slug: healthy-food.hk
    type: rss
    url: https://www.healthy-food.hk/?feed=rss2
    webhook: rss
    parser: auto

  - name: Google台灣官方部落格 RSS
    slug: google_blog_tw
    type: rss
    url: https://blog.google/intl/zh-tw/rss/
    webhook: rss
    parser: auto

  - name: Google The Keyword RSS
    slug: blog.google
    type: rss
    url: https://blog.google/rss/
    webhook: rss
    parser: auto

  - name: 关关难过关关过
    slug: learncodethehardway.com
    type: html
    url: https://learncodethehardway.com/blog/
    webhook: webpage
    selector: "posts  middle"
    parser: auto
    
  - name: hckr news
    slug: hckrnews.com
    type: html
    url: https://hckrnews.com/
    webhook: webpage
    selector: "#entries li.entry"
    parser: auto

  - name: 长沙地铁
    slug: hncsmtr.com_zhaopin
    type: html
    url: https://www.hncsmtr.com/909/932/index.htm
    webhook: webpage
    parser: changsha
    selector: ".datedesc"
    force_encoding: gb18030

  - name: 铁路招聘信息
    slug: rczp.china-railway.com.cn_zhaopin
    type: html
    url: https://rczp.china-railway.com.cn/page/recruitment/rec_info.html
    webhook: webpage
    parser: changsha
    selector: ".rec_table tr td a"
    force_encoding: gb18030