name: webpage-update-reminder

on:
  schedule:
    - cron: "*/10 * * * *"   # 每5分钟
  workflow_dispatch:        # 支持手动运行

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v3

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install requests

      - name: 执行脚本
        run: python check.py

      - name: 提交状态
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add data.json
          git commit -m "update state" || echo "no change"
          git push