name: Site Monitor Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  push:
    paths:
      - "index.html"
      - "monitor.py"
      - "config_monitor.yml"
      - ".github/workflows/monitor.yml"
      - "_datea/**"

permissions:
  contents: write

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Monitor Script
        env:
          FEISHU_HOOK_RSS: ${{ secrets.FEISHU_HOOK_RSS }}
          FEISHU_HOOK_WEBPAGE: ${{ secrets.FEISHU_HOOK_WEBPAGE }}
        run: python monitor.py

      - name: Auto Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add _data/sitedata/*.json
          git commit -m "chore: update logs $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push